movies/urls.py
from django.urls import path
from . import views


app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

pjt05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=100)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)

movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from .models import Movie
from .forms import MovieForm

# Create your views here.
@require_safe
def index(request):
    movies = Movie.objects.order_by('-pk')
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)


@require_http_methods(['POST', 'GET'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()

    context = {
        'form': form
    }
    return render(request, 'movies/form.html', context)


@require_safe
def detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    context = {
        'movie': movie,
    }
    
    return render(request, 'movies/detail.html', context)

@require_http_methods(['POST', 'GET'])
def update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form':form,
        'movie':movie
    }
    return render(request, 'movies/form.html', context)

@require_POST
def delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return redirect('movies:index')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL PAGE</h1>
  <div class="card">
    <img src="{{ movie.poster_path }}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ movie.title }}</h5>
      <p class="card-title">{{ movie.overview }}</p>
    </div>
    <a href="{{ movie.poster_path }}">{{ movie.poster_path }}</a>
  </div>
  <a href="{% url 'movies:update' movie.pk %}">UPDATE</a><br>
  <form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

movies/templates/movies/form.html
{% extends 'base.html' %}

{% block content %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1>Create</h1>
  {% else %}
    <h1>Update</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <a href="{% url 'movies:create' %}">CREATE</a>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
      {% for movie in movies %}
        <div class="card">
          <img src="{{ movie.poster_path }}" class="card-img-top">
          <div class="card-body">
            <a href="{% url 'movies:detail' movie.pk %}">
              <h5 class="card-title">{{ movie.title }}</h5>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

pjt05/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>